// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go-template/internal/biz"
	"go-template/internal/conf"
	"go-template/internal/data/mysql"
	"go-template/internal/server"
	"go-template/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confBiz *conf.Biz, logger log.Logger) (*kratos.App, func(), error) {
	usecaseManager := biz.NewUsecaseManager()
	templateRepo := mysql.NewTemplateRepo(logger)
	templateUsecase := biz.NewTemplateUsecase(logger, usecaseManager, confBiz, templateRepo)
	templateService := service.NewTemplateService(templateUsecase)
	grpcServer := server.NewGRPCServer(confServer, templateService, logger)
	httpServer := server.NewHTTPServer(confServer, confBiz, templateService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
